spring:
  application:
    name: bank-service-application

  datasource:
    url: jdbc:mysql://localhost:3306/camunda_wathiq
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      pool-name: HikariPool-Camunda

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    skip-isolation-level-check: true
    default-serialization-format: application/json
    database:
      type: mysql
      schema-update: true
    generic-properties.properties:
      history-time-to-live: P1D

logging:
  level:
    root: INFO
    org.camunda.bpm: INFO
    com.sudagoarth: DEBUG
