spring:
  application:
    name: bank-service-application
  datasource:
    url: jdbc:h2:file:./data/camunda-h2-database

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo

    database:
      type: h2
      schema-update: true

    default-serialization-format: application/json
    generic-properties.properties:
      history-time-to-live: P1D

logging:
  level:
    root: INFO
    org.camunda.bpm.engine: INFO
    org.camunda.bpm.engine.impl.persistence: WARN
    org.camunda.bpm.engine.impl.interceptor: WARN
    org.camunda.bpm.engine.rest: INFO
    org.camunda.bpm.engine.rest.security: WARN
    org.camunda.bpm.spring.boot: INFO
#    org.camunda.bpm.engine.cmd: DEBUG   # Shows command stack activity
#    org.camunda.bpm.engine.jobexecutor: DEBUG  # Shows async executor activity
    com.sudagoarth: INFO  # Your application package
